# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Study_Week_3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Study_Week_3

 pod 'Toast-Swift', '~> 2.0.0'

end
